import flask
from application import db


class User(db.Document):
    # Document is helpful to define the data type of column fields
    user_id = db.IntField(unique=True)
    first_name = db.StringField(max_length = 50)
    last_name = db.StringField(max_length=50)
    email = db.StringField(max_length=30)
    password = db.StringField(max_length=30)

class Course(db.Document):
    course_id = db.StringField(max_length=10,unique=True)
    title = db.StringField( max_length=100 )
    description = db.StringField( max_length = 255 )
    credits = db.IntField()
    term = db.StringField( max_length=25 )

class Enrollment(db.Document):
    # creating foreign keys to access the required data from other models
    # To Access the default field generated by MongoDB, the variable should be as db.ObjectIdFiels
    user_id = db.IntField()
    course_id = db.StringField( max_length=10 )

